# Generated by Django 3.1.7 on 2021-04-24 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20210313_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.CharField(default='https://restolife.kz/upload/information_system_6/2/2/1/item_22198/information_items_property_25471.jpg', max_length=255)),
                ('address', models.CharField(default='Abay, 170', max_length=100)),
                ('contact', models.CharField(default='+7 (707) 777 77 77', max_length=100)),
                ('avg_cost', models.IntegerField(default=4500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafes', to='api.category')),
            ],
            options={
                'verbose_name': 'Cafe',
                'verbose_name_plural': 'Cafes',
            },
        ),
        migrations.CreateModel(
            name='CafeMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=3000)),
                ('structure', models.CharField(default='Cheese, Milk, Sugar, Salt', max_length=3000)),
                ('time', models.CharField(default='30 minutes', max_length=200)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafemeals', to='api.cafe')),
            ],
            options={
                'verbose_name': 'Cafe Meal',
                'verbose_name_plural': 'Cafe Meals',
            },
        ),
        migrations.CreateModel(
            name='CafeReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafereviews', to='api.cafe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fastfood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.CharField(default='https://restolife.kz/upload/information_system_6/2/2/1/item_22198/information_items_property_25471.jpg', max_length=255)),
                ('address', models.CharField(default='Abay, 170', max_length=100)),
                ('contact', models.CharField(default='+7 (707) 777 77 77', max_length=100)),
                ('avg_cost', models.IntegerField(default=4500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fastfoods', to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='FastfoodMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=3000)),
                ('structure', models.CharField(default='Cheese, Milk, Sugar, Salt', max_length=3000)),
                ('time', models.CharField(default='30 minutes', max_length=200)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fastfoodmeals', to='api.fastfood')),
            ],
            options={
                'verbose_name': 'Fastfood Meal',
                'verbose_name_plural': 'Fastfood Meals',
            },
        ),
        migrations.CreateModel(
            name='FastfoodReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fastfoodreviews', to='api.fastfood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=3000)),
                ('structure', models.CharField(default='Cheese, Milk, Sugar, Salt', max_length=3000)),
                ('time', models.CharField(default='30 minutes', max_length=200)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantmeals', to='api.restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Meal',
                'verbose_name_plural': 'Restaurant Meals',
            },
        ),
        migrations.CreateModel(
            name='RestaurantReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantreviews', to='api.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='structure',
            field=models.CharField(default='Cheese, Milk, Sugar, Salt', max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.CharField(default='30 minutes', max_length=200),
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
