# Generated by Django 3.0.1 on 2021-04-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210424_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='info',
            field=models.CharField(default='The best place', max_length=2000),
        ),
    ]
