# Generated by Django 3.0.1 on 2021-04-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_restaurant_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='info',
            field=models.CharField(default='The best place', max_length=2000),
        ),
        migrations.AddField(
            model_name='fastfood',
            name='info',
            field=models.CharField(default='The best place', max_length=2000),
        ),
    ]
